# Generated by Django 5.0.3 on 2024-03-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp6', '0002_author_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
